theme = "base16_default"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.insert."+"]
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"

# invert `j` and `k` in view mode
[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
