theme = "custom_github_dark"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
true-color = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.file-picker]
hidden = false

[keys.normal]
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"

[keys.insert]
j = { k = "normal_mode" }

[keys.insert."+"]
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
